filter:
    excluded_paths:
        - tests/*

checks:
    php: true

coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true
build:
    environment:
        variables:
            SYMFONY_PHPUNIT_REMOVE_RETURN_TYPEHINT: '1'
    tests:
        override:
            - command: vendor/bin/simple-phpunit --coverage-clover=clover.xml
              coverage:
                  file: clover.xml
                  format: clover
