filter:
    excluded_paths:
        - 'tests/*'
checks:
    php: true
coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true
build:
    tests:
        override:
            -
                coverage:
                    file: 'build/clover.xml'
                    format: 'clover'
