hct_swagger_ui_default:
  path:     /
  defaults: { _controller: HypeCodeTeam\SwaggerUiBundle\Controller\DocsController::indexAction }
  methods: [GET]

hct_swagger_ui_swagger_file:
  path:     /file/{fileName}
  requirements:
    fileName: .+
  defaults: { _controller: HypeCodeTeam\SwaggerUiBundle\Controller\DocsController::swaggerFileAction }
  methods: [GET]

hct_swagger_ui_redirect:
  path:     /{fileName}
  requirements:
    fileName: .+
  defaults: { _controller: HypeCodeTeam\SwaggerUiBundle\Controller\DocsController::redirectAction }
  methods: [GET]
