services:
  HypeCodeTeam\SwaggerUiBundle\Controller\DocsController:
    autowire: true
    autoconfigure: true
    public: true
    tags: ['controller.service_arguments']
    bind:
      $swaggerFiles: '%hct_swagger_ui.files%'
      $directory: '%hct_swagger_ui.directory%'
      $assetUrlPath: '%hct_swagger_ui.assetUrlPath%'
      $configFile: '%hct_swagger_ui.configFile%'
